url: http://localhost:8080/v1/graphql
headers:
  X-Hasura-Admin-Secret: my-secret
queries:
  - name: SearchAlbumsWithArtist
    duration: 10
    rps: 400
    assert:
      results: 7
    query: |
      query SearchAlbumsWithArtist {
        albums(where: {title: {_like: "%Rock%"}}) {
          id
          title
          artist {
            name
            id
          }
        }
      }
  - name: AlbumByPK
    duration: 20
    rps: 400
    assert:
      results: 1
    query: |
      query AlbumByPK {
        albums_by_pk(id: 1) {
          id
          title
        }
      }
  - name: AlbumsArtistTracksGenreAll
    amount: 1000
    connections: 20
    query: |
      query AlbumsArtistTracksGenreAll {
        albums {
          id
          title
          artist {
            id
            name
          }
          tracks {
            id
            name
            genre {
              name
            }
          }
        }
      }
